name: Build Single File Bundle

on:
  push:
    branches: ["single-file-build"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build single file bundle
        run: npm run build

      - name: Upload Single-File Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apps-script-bundle
          path: dist/index.html
          retention-days: 7
